<?xml version="1.0" ?>
<testsuite errors="0" failures="0" name="sys_update.check_update_test-20180424202053" tests="2" time="161.171">
	<testcase classname="sys_update.check_update_test" name="test_01_nav_sys_update" time="62.707"/>
	<testcase classname="sys_update.check_update_test" name="test_02_check_update_now" time="98.464"/>
	<system-out>
<![CDATA[the Page now is: Update
Taking screenshot for sys_update-test_01_nav_sys_update
There is an unexpected issue
Taking screenshot for sys_update-test_02_check_update_now
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
